language: python

python:
  - "2.7"
  - "3.4"

before_install:
  - sudo apt-get install liblapack-dev gfortran python-scipy libblas-dev libsuitesparse-dev swig
  - sudo ln -Tsf /{run,dev}/shm
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then export PATH=/home/travis/miniconda/bin:$PATH; else export PATH=/home/travis/miniconda3/bin:$PATH; fi

install:
  - conda create -n testenv --yes pip python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install --yes jupyter pyzmq numpy scipy nose matplotlib pandas Cython patsy statsmodels

  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then conda install --yes mock enum34; fi
  - pip install --no-deps numdifftools
  - pip install git+https://github.com/Theano/Theano.git
  - pip install git+https://github.com/mahmoudimus/nose-timer.git
  - python setup.py build_ext --inplace

env:
  - TESTCMD=" -vv --with-timer -e test_examples -e test_distributions"
  - TESTCMD=" -vv --with-timer pymc3.tests.test_distributions"
  - TESTCMD=" -vv --with-timer pymc3.tests.test_examples:test_examples0"
  - TESTCMD=" -vv --with-timer pymc3.tests.test_examples:test_examples1"
  - TESTCMD=" -vv --with-timer pymc3.tests.test_examples:test_examples2"
script:
  - nosetests $TESTCMD
