language: python
python:
  - "2.7"
  - "3.3"
before_install:
  - sudo apt-get install liblapack-dev gfortran python-scipy libblas-dev libsuitesparse-dev swig
  - sudo rmdir /dev/shm
  - sudo ln -Tsf /{run,dev}/shm
install:
  - pip install git+https://github.com/numpy/numpy.git
  - pip install scipy
  - pip install matplotlib
  - pip install git+https://github.com/Theano/Theano.git
  - pip install pandas
  - pip install numdifftools
  - pip install Cython
  - pip install scikits.sparse
  - pip install patsy
  - pip install statsmodels
  - python setup.py build_ext --inplace
  - pip install git+git@github.com:jsalvatier/nose-timer.git
env: 
  - TESTCMD="nosetests -vv --with-timer --timer-verbose -e test_glm -e test_examples -e test_distributions"
  - TESTCMD="nosetests -vv --with-timer --timer-verbose pymc.tests.test_examples"
  - TESTCMD="nosetests -vv --with-timer --timer-verbose pymc.tests.test_distributions"
script: "$TESTCMD"
