site_name: PyMC3
repo_url: https://github.com/pymc-devs/pymc3
site_author: PyMC devs
markdown_extensions: ['extra', 'mathjax']
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','js/mathjaxhelper.js']

pages:
- ['index.md', 'Overview']
- ['getting_started.md', 'Tutorial', 'Getting started']
- ['BEST.md', 'Examples', 'BEST']
- ['stochastic_volatility.md', 'Examples', 'Stochastic Volatility']
- ['hierarchical.md', 'Examples', 'Hierarchical model']
- ['GLM-blog-linear.md', 'Examples', 'Linear Regression']
- ['GLM-blog-robust.md', 'Examples', 'Robust Regression']
- ['glm_hierarchical.md', 'Examples', 'Hierarchical linear regression']
- ['pmf-pymc.md', 'Examples', 'Probabilistic Matrix Factorization']
