site_name: PyMC3
repo_url: https://github.com/pymc-devs/pymc
site_author: PyMC devs

pages:
- ['index.md', 'Overview']
- ['getting_started.md', 'Tutorial', 'Getting started']
- ['BEST.md', 'Examples', 'BEST']
- ['stochastic_volatility.md', 'Examples', 'Stochastic Volatility']
- ['hierarchical.md', 'Examples', 'Hierarchical']
