name: arviz-compatibility

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pytest:
    strategy:
      matrix:
        os: [ubuntu-18.04]
        floatx: [float64]
        test-subset:
          - pymc3/tests/test_sampling.py
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      TEST_SUBSET: ${{ matrix.test-subset }}
      THEANO_FLAGS: floatX=${{ matrix.floatx }},gcc.cxxflags='-march=native'
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if environment-dev-py38.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('conda-envs/environment-dev-py38.yml') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pymc3-dev-py38
          channel-priority: strict
          environment-file: conda-envs/environment-dev-py38.yml
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: Install pymc3
        run: |
          conda activate pymc3-dev-py38
          pip install -e .
          python --version
      - name: Install latest arviz
        run: |
          conda activate pymc3-dev-py38
          conda remove arviz -y
          pip install git+git://github.com/arviz-devs/arviz.git
      - name: Run tests
        run: |
          python -m pytest -vv --cov=pymc3 --cov-report=xml --cov-report term --durations=50 $TEST_SUBSET
